  Iteration information for myTAO_ solve.
  0 TAO,  Function value: 0.0356672,  Residual: 0.000147063 
  1 TAO,  Function value: 0.0329552,  Residual: 0.000136595 
  2 TAO,  Function value: 0.0320718,  Residual: 0.000135971 

 The parameters: 
 <Parameter set "para" containing 7 parameter(s) and parameter set(s)>

 hmax = 0.005000; hmin = 0.005000; num_cells = 5996.000000; num_vertices = 3135.000000
Traction forces: g_L1 = (0, 0); g_L2 = (0, 0); g_T3 = (0.000, -1.000); g_T4 = (0.000, -1.000); g_R5 = (0, 0); g_R6 = (0, 0); g_R7 = (0, 0); g_B8 = (0, 0);  g_B9 = (0, 0)
WARNING: user expression has not supplied value_shape method or an element. Assuming scalar element.

 The parameters: 
 <Parameter set "para" containing 7 parameter(s) and parameter set(s)>

 hmax = 0.005000; hmin = 0.005000; num_cells = 6205.000000; num_vertices = 3225.000000
Traction forces: g_L1 = (0, 0); g_L2 = (0, 0); g_T3 = (0.000, -1.000); g_T4 = (0.000, -1.000); g_R5 = (0, 0); g_R6 = (0, 0); g_R7 = (0, 0); g_B8 = (0, 0);  g_B9 = (0, 0)
WARNING: user expression has not supplied value_shape method or an element. Assuming scalar element.

 The parameters: 
 <Parameter set "para" containing 7 parameter(s) and parameter set(s)>

 hmax = 0.005000; hmin = 0.005000; num_cells = 6271.000000; num_vertices = 3270.000000
Traction forces: g_L1 = (0, 0); g_L2 = (0, 0); g_T3 = (0.000, -1.000); g_T4 = (0.000, -1.000); g_R5 = (0, 0); g_R6 = (0, 0); g_R7 = (0, 0); g_B8 = (0, 0);  g_B9 = (0, 0)
WARNING: user expression has not supplied value_shape method or an element. Assuming scalar element.

 The parameters: 
 <Parameter set "para" containing 7 parameter(s) and parameter set(s)>

 hmax = 0.005000; hmin = 0.005000; num_cells = 6142.000000; num_vertices = 3206.000000
Traction forces: g_L1 = (0, 0); g_L2 = (0, 0); g_T3 = (0.000, -1.000); g_T4 = (0.000, -1.000); g_R5 = (0, 0); g_R6 = (0, 0); g_R7 = (0, 0); g_B8 = (0, 0);  g_B9 = (0, 0)
WARNING: user expression has not supplied value_shape method or an element. Assuming scalar element.

 The parameters: 
 <Parameter set "para" containing 7 parameter(s) and parameter set(s)>

 hmax = 0.005000; hmin = 0.005000; num_cells = 6298.000000; num_vertices = 3274.000000
Traction forces: g_L1 = (0, 0); g_L2 = (0, 0); g_T3 = (0.000, -1.000); g_T4 = (0.000, -1.000); g_R5 = (0, 0); g_R6 = (0, 0); g_R7 = (0, 0); g_B8 = (0, 0);  g_B9 = (0, 0)
WARNING: user expression has not supplied value_shape method or an element. Assuming scalar element.

 The parameters: 
 <Parameter set "para" containing 7 parameter(s) and parameter set(s)>

 hmax = 0.005000; hmin = 0.005000; num_cells = 5850.000000; num_vertices = 3044.000000
Traction forces: g_L1 = (0, 0); g_L2 = (0, 0); g_T3 = (0.000, -1.000); g_T4 = (0.000, -1.000); g_R5 = (0, 0); g_R6 = (0, 0); g_R7 = (0, 0); g_B8 = (0, 0);  g_B9 = (0, 0)
WARNING: user expression has not supplied value_shape method or an element. Assuming scalar element.

 The parameters: 
 <Parameter set "para" containing 7 parameter(s) and parameter set(s)>

 hmax = 0.005000; hmin = 0.005000; num_cells = 5968.000000; num_vertices = 3104.000000
Traction forces: g_L1 = (0, 0); g_L2 = (0, 0); g_T3 = (0.000, -1.000); g_T4 = (0.000, -1.000); g_R5 = (0, 0); g_R6 = (0, 0); g_R7 = (0, 0); g_B8 = (0, 0);  g_B9 = (0, 0)
WARNING: user expression has not supplied value_shape method or an element. Assuming scalar element.

 The parameters: 
 <Parameter set "para" containing 7 parameter(s) and parameter set(s)>

 hmax = 0.005000; hmin = 0.005000; num_cells = 6182.000000; num_vertices = 3231.000000
Traction forces: g_L1 = (0, 0); g_L2 = (0, 0); g_T3 = (0.000, -1.000); g_T4 = (0.000, -1.000); g_R5 = (0, 0); g_R6 = (0, 0); g_R7 = (0, 0); g_B8 = (0, 0);  g_B9 = (0, 0)
WARNING: user expression has not supplied value_shape method or an element. Assuming scalar element.
Traceback (most recent call last):
  File "AS_phase_field_opt.py", line 806, in <module>
    main()
  File "AS_phase_field_opt.py", line 138, in main
    iter = solver_TAO_alpha.solve(problem_alpha, alpha.vector(), lb_alpha.vector(), ub_alpha.vector())
  File "AS_phase_field_opt.py", line 311, in f
    self.solve_pde()
  File "AS_phase_field_opt.py", line 469, in solve_pde
    self.solver_pde.solve()
RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to solve nonlinear system with PETScSNESSolver.
*** Reason:  Solver did not converge.
*** Where:   This error was encountered inside PETScSNESSolver.cpp.
*** Process: 2
*** 
*** DOLFIN version: 2018.1.0
*** Git changeset:  948dc42cc4e06ed9227d0201ad50f94ac94cbf9f
*** -------------------------------------------------------------------------

Traceback (most recent call last):
  File "AS_phase_field_opt.py", line 806, in <module>
    main()
  File "AS_phase_field_opt.py", line 138, in main
    iter = solver_TAO_alpha.solve(problem_alpha, alpha.vector(), lb_alpha.vector(), ub_alpha.vector())
  File "AS_phase_field_opt.py", line 311, in f
    self.solve_pde()
  File "AS_phase_field_opt.py", line 469, in solve_pde
    self.solver_pde.solve()
RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to solve nonlinear system with PETScSNESSolver.
*** Reason:  Solver did not converge.
*** Where:   This error was encountered inside PETScSNESSolver.cpp.
*** Process: 3
*** 
*** DOLFIN version: 2018.1.0
*** Git changeset:  948dc42cc4e06ed9227d0201ad50f94ac94cbf9f
*** -------------------------------------------------------------------------

Traceback (most recent call last):
  File "AS_phase_field_opt.py", line 806, in <module>
    main()
  File "AS_phase_field_opt.py", line 138, in main
    iter = solver_TAO_alpha.solve(problem_alpha, alpha.vector(), lb_alpha.vector(), ub_alpha.vector())
  File "AS_phase_field_opt.py", line 311, in f
    self.solve_pde()
  File "AS_phase_field_opt.py", line 469, in solve_pde
    self.solver_pde.solve()
RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to solve nonlinear system with PETScSNESSolver.
*** Reason:  Solver did not converge.
*** Where:   This error was encountered inside PETScSNESSolver.cpp.
*** Process: 0
*** 
*** DOLFIN version: 2018.1.0
*** Git changeset:  948dc42cc4e06ed9227d0201ad50f94ac94cbf9f
*** -------------------------------------------------------------------------

Traceback (most recent call last):
  File "AS_phase_field_opt.py", line 806, in <module>
    main()
  File "AS_phase_field_opt.py", line 138, in main
    iter = solver_TAO_alpha.solve(problem_alpha, alpha.vector(), lb_alpha.vector(), ub_alpha.vector())
  File "AS_phase_field_opt.py", line 311, in f
    self.solve_pde()
  File "AS_phase_field_opt.py", line 469, in solve_pde
    self.solver_pde.solve()
RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to solve nonlinear system with PETScSNESSolver.
*** Reason:  Solver did not converge.
*** Where:   This error was encountered inside PETScSNESSolver.cpp.
*** Process: 7
*** 
*** DOLFIN version: 2018.1.0
*** Git changeset:  948dc42cc4e06ed9227d0201ad50f94ac94cbf9f
*** -------------------------------------------------------------------------

Traceback (most recent call last):
  File "AS_phase_field_opt.py", line 806, in <module>
    main()
  File "AS_phase_field_opt.py", line 138, in main
    iter = solver_TAO_alpha.solve(problem_alpha, alpha.vector(), lb_alpha.vector(), ub_alpha.vector())
  File "AS_phase_field_opt.py", line 311, in f
    self.solve_pde()
  File "AS_phase_field_opt.py", line 469, in solve_pde
    self.solver_pde.solve()
RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to solve nonlinear system with PETScSNESSolver.
*** Reason:  Solver did not converge.
*** Where:   This error was encountered inside PETScSNESSolver.cpp.
*** Process: 1
*** 
*** DOLFIN version: 2018.1.0
*** Git changeset:  948dc42cc4e06ed9227d0201ad50f94ac94cbf9f
*** -------------------------------------------------------------------------

Traceback (most recent call last):
  File "AS_phase_field_opt.py", line 806, in <module>
    main()
  File "AS_phase_field_opt.py", line 138, in main
    iter = solver_TAO_alpha.solve(problem_alpha, alpha.vector(), lb_alpha.vector(), ub_alpha.vector())
  File "AS_phase_field_opt.py", line 311, in f
    self.solve_pde()
  File "AS_phase_field_opt.py", line 469, in solve_pde
    self.solver_pde.solve()
RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to solve nonlinear system with PETScSNESSolver.
*** Reason:  Solver did not converge.
*** Where:   This error was encountered inside PETScSNESSolver.cpp.
*** Process: 4
*** 
*** DOLFIN version: 2018.1.0
*** Git changeset:  948dc42cc4e06ed9227d0201ad50f94ac94cbf9f
*** -------------------------------------------------------------------------

Traceback (most recent call last):
  File "AS_phase_field_opt.py", line 806, in <module>
    main()
  File "AS_phase_field_opt.py", line 138, in main
    iter = solver_TAO_alpha.solve(problem_alpha, alpha.vector(), lb_alpha.vector(), ub_alpha.vector())
  File "AS_phase_field_opt.py", line 311, in f
    self.solve_pde()
  File "AS_phase_field_opt.py", line 469, in solve_pde
    self.solver_pde.solve()
RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to solve nonlinear system with PETScSNESSolver.
*** Reason:  Solver did not converge.
*** Where:   This error was encountered inside PETScSNESSolver.cpp.
*** Process: 6
*** 
*** DOLFIN version: 2018.1.0
*** Git changeset:  948dc42cc4e06ed9227d0201ad50f94ac94cbf9f
*** -------------------------------------------------------------------------

Traceback (most recent call last):
  File "AS_phase_field_opt.py", line 806, in <module>
    main()
  File "AS_phase_field_opt.py", line 138, in main
    iter = solver_TAO_alpha.solve(problem_alpha, alpha.vector(), lb_alpha.vector(), ub_alpha.vector())
  File "AS_phase_field_opt.py", line 311, in f
    self.solve_pde()
  File "AS_phase_field_opt.py", line 469, in solve_pde
    self.solver_pde.solve()
RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to solve nonlinear system with PETScSNESSolver.
*** Reason:  Solver did not converge.
*** Where:   This error was encountered inside PETScSNESSolver.cpp.
*** Process: 5
*** 
*** DOLFIN version: 2018.1.0
*** Git changeset:  948dc42cc4e06ed9227d0201ad50f94ac94cbf9f
*** -------------------------------------------------------------------------

  Iteration information for myTAO_ solve.
  0 TAO,  Function value: 0.0356672,  Residual: 0.000147063 
  1 TAO,  Function value: 0.0329552,  Residual: 0.000136595 
  2 TAO,  Function value: 0.0320718,  Residual: 0.000135971 

 The parameters: 
 <Parameter set "para" containing 7 parameter(s) and parameter set(s)>

 hmax = 0.005000; hmin = 0.005000; num_cells = 6074.000000; num_vertices = 3153.000000
Traction forces: g_L1 = (0, 0); g_L2 = (0, 0); g_T3 = (0.000, -1.000); g_T4 = (0.000, -1.000); g_R5 = (0, 0); g_R6 = (0, 0); g_R7 = (0, 0); g_B8 = (0, 0);  g_B9 = (0, 0)
WARNING: user expression has not supplied value_shape method or an element. Assuming scalar element.

 The parameters: 
 <Parameter set "para" containing 7 parameter(s) and parameter set(s)>

 hmax = 0.005000; hmin = 0.005000; num_cells = 6146.000000; num_vertices = 3194.000000
Traction forces: g_L1 = (0, 0); g_L2 = (0, 0); g_T3 = (0.000, -1.000); g_T4 = (0.000, -1.000); g_R5 = (0, 0); g_R6 = (0, 0); g_R7 = (0, 0); g_B8 = (0, 0);  g_B9 = (0, 0)
WARNING: user expression has not supplied value_shape method or an element. Assuming scalar element.

 The parameters: 
 <Parameter set "para" containing 7 parameter(s) and parameter set(s)>

 hmax = 0.005000; hmin = 0.005000; num_cells = 6131.000000; num_vertices = 3195.000000
Traction forces: g_L1 = (0, 0); g_L2 = (0, 0); g_T3 = (0.000, -1.000); g_T4 = (0.000, -1.000); g_R5 = (0, 0); g_R6 = (0, 0); g_R7 = (0, 0); g_B8 = (0, 0);  g_B9 = (0, 0)
WARNING: user expression has not supplied value_shape method or an element. Assuming scalar element.

 The parameters: 
 <Parameter set "para" containing 7 parameter(s) and parameter set(s)>

 hmax = 0.005000; hmin = 0.005000; num_cells = 6107.000000; num_vertices = 3177.000000
Traction forces: g_L1 = (0, 0); g_L2 = (0, 0); g_T3 = (0.000, -1.000); g_T4 = (0.000, -1.000); g_R5 = (0, 0); g_R6 = (0, 0); g_R7 = (0, 0); g_B8 = (0, 0);  g_B9 = (0, 0)
WARNING: user expression has not supplied value_shape method or an element. Assuming scalar element.

 The parameters: 
 <Parameter set "para" containing 7 parameter(s) and parameter set(s)>

 hmax = 0.005000; hmin = 0.005000; num_cells = 5833.000000; num_vertices = 3050.000000
Traction forces: g_L1 = (0, 0); g_L2 = (0, 0); g_T3 = (0.000, -1.000); g_T4 = (0.000, -1.000); g_R5 = (0, 0); g_R6 = (0, 0); g_R7 = (0, 0); g_B8 = (0, 0);  g_B9 = (0, 0)
WARNING: user expression has not supplied value_shape method or an element. Assuming scalar element.

 The parameters: 
 <Parameter set "para" containing 7 parameter(s) and parameter set(s)>

 hmax = 0.005000; hmin = 0.005000; num_cells = 6322.000000; num_vertices = 3297.000000
Traction forces: g_L1 = (0, 0); g_L2 = (0, 0); g_T3 = (0.000, -1.000); g_T4 = (0.000, -1.000); g_R5 = (0, 0); g_R6 = (0, 0); g_R7 = (0, 0); g_B8 = (0, 0);  g_B9 = (0, 0)
WARNING: user expression has not supplied value_shape method or an element. Assuming scalar element.

 The parameters: 
 <Parameter set "para" containing 7 parameter(s) and parameter set(s)>

 hmax = 0.005000; hmin = 0.005000; num_cells = 6165.000000; num_vertices = 3228.000000
Traction forces: g_L1 = (0, 0); g_L2 = (0, 0); g_T3 = (0.000, -1.000); g_T4 = (0.000, -1.000); g_R5 = (0, 0); g_R6 = (0, 0); g_R7 = (0, 0); g_B8 = (0, 0);  g_B9 = (0, 0)
WARNING: user expression has not supplied value_shape method or an element. Assuming scalar element.

 The parameters: 
 <Parameter set "para" containing 7 parameter(s) and parameter set(s)>

 hmax = 0.005000; hmin = 0.005000; num_cells = 6166.000000; num_vertices = 3204.000000
Traction forces: g_L1 = (0, 0); g_L2 = (0, 0); g_T3 = (0.000, -1.000); g_T4 = (0.000, -1.000); g_R5 = (0, 0); g_R6 = (0, 0); g_R7 = (0, 0); g_B8 = (0, 0);  g_B9 = (0, 0)
WARNING: user expression has not supplied value_shape method or an element. Assuming scalar element.
Traceback (most recent call last):
  File "AS_phase_field_opt.py", line 806, in <module>
    main()
  File "AS_phase_field_opt.py", line 138, in main
    iter = solver_TAO_alpha.solve(problem_alpha, alpha.vector(), lb_alpha.vector(), ub_alpha.vector())
  File "AS_phase_field_opt.py", line 311, in f
    self.solve_pde()
  File "AS_phase_field_opt.py", line 469, in solve_pde
    self.solver_pde.solve()
RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to solve nonlinear system with PETScSNESSolver.
*** Reason:  Solver did not converge.
*** Where:   This error was encountered inside PETScSNESSolver.cpp.
*** Process: 2
*** 
*** DOLFIN version: 2018.1.0
*** Git changeset:  948dc42cc4e06ed9227d0201ad50f94ac94cbf9f
*** -------------------------------------------------------------------------

Traceback (most recent call last):
  File "AS_phase_field_opt.py", line 806, in <module>
    main()
  File "AS_phase_field_opt.py", line 138, in main
    iter = solver_TAO_alpha.solve(problem_alpha, alpha.vector(), lb_alpha.vector(), ub_alpha.vector())
  File "AS_phase_field_opt.py", line 311, in f
    self.solve_pde()
  File "AS_phase_field_opt.py", line 469, in solve_pde
    self.solver_pde.solve()
RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to solve nonlinear system with PETScSNESSolver.
*** Reason:  Solver did not converge.
*** Where:   This error was encountered inside PETScSNESSolver.cpp.
*** Process: 1
*** 
*** DOLFIN version: 2018.1.0
*** Git changeset:  948dc42cc4e06ed9227d0201ad50f94ac94cbf9f
*** -------------------------------------------------------------------------

Traceback (most recent call last):
  File "AS_phase_field_opt.py", line 806, in <module>
    main()
  File "AS_phase_field_opt.py", line 138, in main
    iter = solver_TAO_alpha.solve(problem_alpha, alpha.vector(), lb_alpha.vector(), ub_alpha.vector())
  File "AS_phase_field_opt.py", line 311, in f
    self.solve_pde()
  File "AS_phase_field_opt.py", line 469, in solve_pde
    self.solver_pde.solve()
RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to solve nonlinear system with PETScSNESSolver.
*** Reason:  Solver did not converge.
*** Where:   This error was encountered inside PETScSNESSolver.cpp.
*** Process: 0
*** 
*** DOLFIN version: 2018.1.0
*** Git changeset:  948dc42cc4e06ed9227d0201ad50f94ac94cbf9f
*** -------------------------------------------------------------------------

Traceback (most recent call last):
  File "AS_phase_field_opt.py", line 806, in <module>
    main()
  File "AS_phase_field_opt.py", line 138, in main
    iter = solver_TAO_alpha.solve(problem_alpha, alpha.vector(), lb_alpha.vector(), ub_alpha.vector())
  File "AS_phase_field_opt.py", line 311, in f
    self.solve_pde()
  File "AS_phase_field_opt.py", line 469, in solve_pde
    self.solver_pde.solve()
RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to solve nonlinear system with PETScSNESSolver.
*** Reason:  Solver did not converge.
*** Where:   This error was encountered inside PETScSNESSolver.cpp.
*** Process: 5
*** 
*** DOLFIN version: 2018.1.0
*** Git changeset:  948dc42cc4e06ed9227d0201ad50f94ac94cbf9f
*** -------------------------------------------------------------------------

Traceback (most recent call last):
  File "AS_phase_field_opt.py", line 806, in <module>
    main()
  File "AS_phase_field_opt.py", line 138, in main
    iter = solver_TAO_alpha.solve(problem_alpha, alpha.vector(), lb_alpha.vector(), ub_alpha.vector())
  File "AS_phase_field_opt.py", line 311, in f
    self.solve_pde()
  File "AS_phase_field_opt.py", line 469, in solve_pde
    self.solver_pde.solve()
RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to solve nonlinear system with PETScSNESSolver.
*** Reason:  Solver did not converge.
*** Where:   This error was encountered inside PETScSNESSolver.cpp.
*** Process: 4
*** 
*** DOLFIN version: 2018.1.0
*** Git changeset:  948dc42cc4e06ed9227d0201ad50f94ac94cbf9f
*** -------------------------------------------------------------------------

Traceback (most recent call last):
  File "AS_phase_field_opt.py", line 806, in <module>
    main()
  File "AS_phase_field_opt.py", line 138, in main
    iter = solver_TAO_alpha.solve(problem_alpha, alpha.vector(), lb_alpha.vector(), ub_alpha.vector())
  File "AS_phase_field_opt.py", line 311, in f
    self.solve_pde()
  File "AS_phase_field_opt.py", line 469, in solve_pde
    self.solver_pde.solve()
RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to solve nonlinear system with PETScSNESSolver.
*** Reason:  Solver did not converge.
*** Where:   This error was encountered inside PETScSNESSolver.cpp.
*** Process: 6
*** 
*** DOLFIN version: 2018.1.0
*** Git changeset:  948dc42cc4e06ed9227d0201ad50f94ac94cbf9f
*** -------------------------------------------------------------------------

Traceback (most recent call last):
  File "AS_phase_field_opt.py", line 806, in <module>
    main()
  File "AS_phase_field_opt.py", line 138, in main
    iter = solver_TAO_alpha.solve(problem_alpha, alpha.vector(), lb_alpha.vector(), ub_alpha.vector())
  File "AS_phase_field_opt.py", line 311, in f
    self.solve_pde()
  File "AS_phase_field_opt.py", line 469, in solve_pde
    self.solver_pde.solve()
RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to solve nonlinear system with PETScSNESSolver.
*** Reason:  Solver did not converge.
*** Where:   This error was encountered inside PETScSNESSolver.cpp.
*** Process: 7
*** 
*** DOLFIN version: 2018.1.0
*** Git changeset:  948dc42cc4e06ed9227d0201ad50f94ac94cbf9f
*** -------------------------------------------------------------------------

Traceback (most recent call last):
  File "AS_phase_field_opt.py", line 806, in <module>
    main()
  File "AS_phase_field_opt.py", line 138, in main
    iter = solver_TAO_alpha.solve(problem_alpha, alpha.vector(), lb_alpha.vector(), ub_alpha.vector())
  File "AS_phase_field_opt.py", line 311, in f
    self.solve_pde()
  File "AS_phase_field_opt.py", line 469, in solve_pde
    self.solver_pde.solve()
RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to solve nonlinear system with PETScSNESSolver.
*** Reason:  Solver did not converge.
*** Where:   This error was encountered inside PETScSNESSolver.cpp.
*** Process: 3
*** 
*** DOLFIN version: 2018.1.0
*** Git changeset:  948dc42cc4e06ed9227d0201ad50f94ac94cbf9f
*** -------------------------------------------------------------------------

  Iteration information for myTAO_ solve.
  0 TAO,  Function value: 0.0356672,  Residual: 0.000147063 
  1 TAO,  Function value: 0.0329552,  Residual: 0.000136595 
  2 TAO,  Function value: 0.0320718,  Residual: 0.000135971 

 The parameters: 
 <Parameter set "para" containing 7 parameter(s) and parameter set(s)>

 hmax = 0.005000; hmin = 0.005000; num_cells = 6253.000000; num_vertices = 3252.000000
Traction forces: g_L1 = (0, 0); g_L2 = (0, 0); g_T3 = (0.000, -1.000); g_T4 = (0.000, -1.000); g_R5 = (0, 0); g_R6 = (0, 0); g_R7 = (0, 0); g_B8 = (0, 0);  g_B9 = (0, 0)
WARNING: user expression has not supplied value_shape method or an element. Assuming scalar element.

 The parameters: 
 <Parameter set "para" containing 7 parameter(s) and parameter set(s)>

 hmax = 0.005000; hmin = 0.005000; num_cells = 6159.000000; num_vertices = 3201.000000
Traction forces: g_L1 = (0, 0); g_L2 = (0, 0); g_T3 = (0.000, -1.000); g_T4 = (0.000, -1.000); g_R5 = (0, 0); g_R6 = (0, 0); g_R7 = (0, 0); g_B8 = (0, 0);  g_B9 = (0, 0)
WARNING: user expression has not supplied value_shape method or an element. Assuming scalar element.

 The parameters: 
 <Parameter set "para" containing 7 parameter(s) and parameter set(s)>

 hmax = 0.005000; hmin = 0.005000; num_cells = 6149.000000; num_vertices = 3202.000000
Traction forces: g_L1 = (0, 0); g_L2 = (0, 0); g_T3 = (0.000, -1.000); g_T4 = (0.000, -1.000); g_R5 = (0, 0); g_R6 = (0, 0); g_R7 = (0, 0); g_B8 = (0, 0);  g_B9 = (0, 0)
WARNING: user expression has not supplied value_shape method or an element. Assuming scalar element.

 The parameters: 
 <Parameter set "para" containing 7 parameter(s) and parameter set(s)>

 hmax = 0.005000; hmin = 0.005000; num_cells = 5897.000000; num_vertices = 3086.000000
Traction forces: g_L1 = (0, 0); g_L2 = (0, 0); g_T3 = (0.000, -1.000); g_T4 = (0.000, -1.000); g_R5 = (0, 0); g_R6 = (0, 0); g_R7 = (0, 0); g_B8 = (0, 0);  g_B9 = (0, 0)
WARNING: user expression has not supplied value_shape method or an element. Assuming scalar element.

 The parameters: 
 <Parameter set "para" containing 7 parameter(s) and parameter set(s)>

 hmax = 0.005000; hmin = 0.005000; num_cells = 5952.000000; num_vertices = 3091.000000
Traction forces: g_L1 = (0, 0); g_L2 = (0, 0); g_T3 = (0.000, -1.000); g_T4 = (0.000, -1.000); g_R5 = (0, 0); g_R6 = (0, 0); g_R7 = (0, 0); g_B8 = (0, 0);  g_B9 = (0, 0)
WARNING: user expression has not supplied value_shape method or an element. Assuming scalar element.

 The parameters: 
 <Parameter set "para" containing 7 parameter(s) and parameter set(s)>

 hmax = 0.005000; hmin = 0.005000; num_cells = 6311.000000; num_vertices = 3278.000000
Traction forces: g_L1 = (0, 0); g_L2 = (0, 0); g_T3 = (0.000, -1.000); g_T4 = (0.000, -1.000); g_R5 = (0, 0); g_R6 = (0, 0); g_R7 = (0, 0); g_B8 = (0, 0);  g_B9 = (0, 0)
WARNING: user expression has not supplied value_shape method or an element. Assuming scalar element.

 The parameters: 
 <Parameter set "para" containing 7 parameter(s) and parameter set(s)>

 hmax = 0.005000; hmin = 0.005000; num_cells = 6380.000000; num_vertices = 3330.000000
Traction forces: g_L1 = (0, 0); g_L2 = (0, 0); g_T3 = (0.000, -1.000); g_T4 = (0.000, -1.000); g_R5 = (0, 0); g_R6 = (0, 0); g_R7 = (0, 0); g_B8 = (0, 0);  g_B9 = (0, 0)
WARNING: user expression has not supplied value_shape method or an element. Assuming scalar element.

 The parameters: 
 <Parameter set "para" containing 7 parameter(s) and parameter set(s)>

 hmax = 0.005000; hmin = 0.005000; num_cells = 5882.000000; num_vertices = 3063.000000
Traction forces: g_L1 = (0, 0); g_L2 = (0, 0); g_T3 = (0.000, -1.000); g_T4 = (0.000, -1.000); g_R5 = (0, 0); g_R6 = (0, 0); g_R7 = (0, 0); g_B8 = (0, 0);  g_B9 = (0, 0)
WARNING: user expression has not supplied value_shape method or an element. Assuming scalar element.
Traceback (most recent call last):
  File "AS_phase_field_opt.py", line 806, in <module>
    main()
  File "AS_phase_field_opt.py", line 138, in main
    iter = solver_TAO_alpha.solve(problem_alpha, alpha.vector(), lb_alpha.vector(), ub_alpha.vector())
  File "AS_phase_field_opt.py", line 311, in f
    self.solve_pde()
  File "AS_phase_field_opt.py", line 469, in solve_pde
    self.solver_pde.solve()
RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to solve nonlinear system with PETScSNESSolver.
*** Reason:  Solver did not converge.
*** Where:   This error was encountered inside PETScSNESSolver.cpp.
*** Process: 7
*** 
*** DOLFIN version: 2018.1.0
*** Git changeset:  948dc42cc4e06ed9227d0201ad50f94ac94cbf9f
*** -------------------------------------------------------------------------

Traceback (most recent call last):
  File "AS_phase_field_opt.py", line 806, in <module>
    main()
  File "AS_phase_field_opt.py", line 138, in main
    iter = solver_TAO_alpha.solve(problem_alpha, alpha.vector(), lb_alpha.vector(), ub_alpha.vector())
  File "AS_phase_field_opt.py", line 311, in f
    self.solve_pde()
  File "AS_phase_field_opt.py", line 469, in solve_pde
    self.solver_pde.solve()
RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to solve nonlinear system with PETScSNESSolver.
*** Reason:  Solver did not converge.
*** Where:   This error was encountered inside PETScSNESSolver.cpp.
*** Process: 0
*** 
*** DOLFIN version: 2018.1.0
*** Git changeset:  948dc42cc4e06ed9227d0201ad50f94ac94cbf9f
*** -------------------------------------------------------------------------

Traceback (most recent call last):
  File "AS_phase_field_opt.py", line 806, in <module>
    main()
  File "AS_phase_field_opt.py", line 138, in main
    iter = solver_TAO_alpha.solve(problem_alpha, alpha.vector(), lb_alpha.vector(), ub_alpha.vector())
  File "AS_phase_field_opt.py", line 311, in f
    self.solve_pde()
  File "AS_phase_field_opt.py", line 469, in solve_pde
    self.solver_pde.solve()
RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to solve nonlinear system with PETScSNESSolver.
*** Reason:  Solver did not converge.
*** Where:   This error was encountered inside PETScSNESSolver.cpp.
*** Process: 2
*** 
*** DOLFIN version: 2018.1.0
*** Git changeset:  948dc42cc4e06ed9227d0201ad50f94ac94cbf9f
*** -------------------------------------------------------------------------

Traceback (most recent call last):
  File "AS_phase_field_opt.py", line 806, in <module>
    main()
  File "AS_phase_field_opt.py", line 138, in main
    iter = solver_TAO_alpha.solve(problem_alpha, alpha.vector(), lb_alpha.vector(), ub_alpha.vector())
  File "AS_phase_field_opt.py", line 311, in f
    self.solve_pde()
  File "AS_phase_field_opt.py", line 469, in solve_pde
    self.solver_pde.solve()
RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to solve nonlinear system with PETScSNESSolver.
*** Reason:  Solver did not converge.
*** Where:   This error was encountered inside PETScSNESSolver.cpp.
*** Process: 1
*** 
*** DOLFIN version: 2018.1.0
*** Git changeset:  948dc42cc4e06ed9227d0201ad50f94ac94cbf9f
*** -------------------------------------------------------------------------

Traceback (most recent call last):
  File "AS_phase_field_opt.py", line 806, in <module>
    main()
  File "AS_phase_field_opt.py", line 138, in main
    iter = solver_TAO_alpha.solve(problem_alpha, alpha.vector(), lb_alpha.vector(), ub_alpha.vector())
  File "AS_phase_field_opt.py", line 311, in f
    self.solve_pde()
  File "AS_phase_field_opt.py", line 469, in solve_pde
    self.solver_pde.solve()
RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to solve nonlinear system with PETScSNESSolver.
*** Reason:  Solver did not converge.
*** Where:   This error was encountered inside PETScSNESSolver.cpp.
*** Process: 4
*** 
*** DOLFIN version: 2018.1.0
*** Git changeset:  948dc42cc4e06ed9227d0201ad50f94ac94cbf9f
*** -------------------------------------------------------------------------

Traceback (most recent call last):
  File "AS_phase_field_opt.py", line 806, in <module>
    main()
  File "AS_phase_field_opt.py", line 138, in main
    iter = solver_TAO_alpha.solve(problem_alpha, alpha.vector(), lb_alpha.vector(), ub_alpha.vector())
  File "AS_phase_field_opt.py", line 311, in f
    self.solve_pde()
  File "AS_phase_field_opt.py", line 469, in solve_pde
    self.solver_pde.solve()
RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to solve nonlinear system with PETScSNESSolver.
*** Reason:  Solver did not converge.
*** Where:   This error was encountered inside PETScSNESSolver.cpp.
*** Process: 6
*** 
*** DOLFIN version: 2018.1.0
*** Git changeset:  948dc42cc4e06ed9227d0201ad50f94ac94cbf9f
*** -------------------------------------------------------------------------

Traceback (most recent call last):
  File "AS_phase_field_opt.py", line 806, in <module>
    main()
  File "AS_phase_field_opt.py", line 138, in main
    iter = solver_TAO_alpha.solve(problem_alpha, alpha.vector(), lb_alpha.vector(), ub_alpha.vector())
  File "AS_phase_field_opt.py", line 311, in f
    self.solve_pde()
  File "AS_phase_field_opt.py", line 469, in solve_pde
    self.solver_pde.solve()
RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to solve nonlinear system with PETScSNESSolver.
*** Reason:  Solver did not converge.
*** Where:   This error was encountered inside PETScSNESSolver.cpp.
*** Process: 5
*** 
*** DOLFIN version: 2018.1.0
*** Git changeset:  948dc42cc4e06ed9227d0201ad50f94ac94cbf9f
*** -------------------------------------------------------------------------

Traceback (most recent call last):
  File "AS_phase_field_opt.py", line 806, in <module>
    main()
  File "AS_phase_field_opt.py", line 138, in main
    iter = solver_TAO_alpha.solve(problem_alpha, alpha.vector(), lb_alpha.vector(), ub_alpha.vector())
  File "AS_phase_field_opt.py", line 311, in f
    self.solve_pde()
  File "AS_phase_field_opt.py", line 469, in solve_pde
    self.solver_pde.solve()
RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to solve nonlinear system with PETScSNESSolver.
*** Reason:  Solver did not converge.
*** Where:   This error was encountered inside PETScSNESSolver.cpp.
*** Process: 3
*** 
*** DOLFIN version: 2018.1.0
*** Git changeset:  948dc42cc4e06ed9227d0201ad50f94ac94cbf9f
*** -------------------------------------------------------------------------

  Iteration information for myTAO_ solve.
  0 TAO,  Function value: 0.0356672,  Residual: 0.000147063 
  1 TAO,  Function value: 0.0329552,  Residual: 0.000136595 
  2 TAO,  Function value: 0.0320718,  Residual: 0.000135971 

 The parameters: 
 <Parameter set "para" containing 7 parameter(s) and parameter set(s)>

 hmax = 0.005000; hmin = 0.005000; num_cells = 6115.000000; num_vertices = 3184.000000
Traction forces: g_L1 = (0, 0); g_L2 = (0, 0); g_T3 = (0.000, -1.000); g_T4 = (0.000, -1.000); g_R5 = (0, 0); g_R6 = (0, 0); g_R7 = (0, 0); g_B8 = (0, 0);  g_B9 = (0, 0)
WARNING: user expression has not supplied value_shape method or an element. Assuming scalar element.

 The parameters: 
 <Parameter set "para" containing 7 parameter(s) and parameter set(s)>

 hmax = 0.005000; hmin = 0.005000; num_cells = 6174.000000; num_vertices = 3213.000000
Traction forces: g_L1 = (0, 0); g_L2 = (0, 0); g_T3 = (0.000, -1.000); g_T4 = (0.000, -1.000); g_R5 = (0, 0); g_R6 = (0, 0); g_R7 = (0, 0); g_B8 = (0, 0);  g_B9 = (0, 0)
WARNING: user expression has not supplied value_shape method or an element. Assuming scalar element.

 The parameters: 
 <Parameter set "para" containing 7 parameter(s) and parameter set(s)>

 hmax = 0.005000; hmin = 0.005000; num_cells = 6342.000000; num_vertices = 3306.000000
Traction forces: g_L1 = (0, 0); g_L2 = (0, 0); g_T3 = (0.000, -1.000); g_T4 = (0.000, -1.000); g_R5 = (0, 0); g_R6 = (0, 0); g_R7 = (0, 0); g_B8 = (0, 0);  g_B9 = (0, 0)
WARNING: user expression has not supplied value_shape method or an element. Assuming scalar element.

 The parameters: 
 <Parameter set "para" containing 7 parameter(s) and parameter set(s)>

 hmax = 0.005000; hmin = 0.005000; num_cells = 5875.000000; num_vertices = 3045.000000
Traction forces: g_L1 = (0, 0); g_L2 = (0, 0); g_T3 = (0.000, -1.000); g_T4 = (0.000, -1.000); g_R5 = (0, 0); g_R6 = (0, 0); g_R7 = (0, 0); g_B8 = (0, 0);  g_B9 = (0, 0)
WARNING: user expression has not supplied value_shape method or an element. Assuming scalar element.

 The parameters: 
 <Parameter set "para" containing 7 parameter(s) and parameter set(s)>

 hmax = 0.005000; hmin = 0.005000; num_cells = 6117.000000; num_vertices = 3195.000000
Traction forces: g_L1 = (0, 0); g_L2 = (0, 0); g_T3 = (0.000, -1.000); g_T4 = (0.000, -1.000); g_R5 = (0, 0); g_R6 = (0, 0); g_R7 = (0, 0); g_B8 = (0, 0);  g_B9 = (0, 0)
WARNING: user expression has not supplied value_shape method or an element. Assuming scalar element.

 The parameters: 
 <Parameter set "para" containing 7 parameter(s) and parameter set(s)>

 hmax = 0.005000; hmin = 0.005000; num_cells = 6186.000000; num_vertices = 3215.000000
Traction forces: g_L1 = (0, 0); g_L2 = (0, 0); g_T3 = (0.000, -1.000); g_T4 = (0.000, -1.000); g_R5 = (0, 0); g_R6 = (0, 0); g_R7 = (0, 0); g_B8 = (0, 0);  g_B9 = (0, 0)
WARNING: user expression has not supplied value_shape method or an element. Assuming scalar element.

 The parameters: 
 <Parameter set "para" containing 7 parameter(s) and parameter set(s)>

 hmax = 0.005000; hmin = 0.005000; num_cells = 6159.000000; num_vertices = 3216.000000
Traction forces: g_L1 = (0, 0); g_L2 = (0, 0); g_T3 = (0.000, -1.000); g_T4 = (0.000, -1.000); g_R5 = (0, 0); g_R6 = (0, 0); g_R7 = (0, 0); g_B8 = (0, 0);  g_B9 = (0, 0)
WARNING: user expression has not supplied value_shape method or an element. Assuming scalar element.

 The parameters: 
 <Parameter set "para" containing 7 parameter(s) and parameter set(s)>

 hmax = 0.005000; hmin = 0.005000; num_cells = 6013.000000; num_vertices = 3125.000000
Traction forces: g_L1 = (0, 0); g_L2 = (0, 0); g_T3 = (0.000, -1.000); g_T4 = (0.000, -1.000); g_R5 = (0, 0); g_R6 = (0, 0); g_R7 = (0, 0); g_B8 = (0, 0);  g_B9 = (0, 0)
WARNING: user expression has not supplied value_shape method or an element. Assuming scalar element.
Traceback (most recent call last):
  File "AS_phase_field_opt.py", line 806, in <module>
    main()
  File "AS_phase_field_opt.py", line 138, in main
    iter = solver_TAO_alpha.solve(problem_alpha, alpha.vector(), lb_alpha.vector(), ub_alpha.vector())
  File "AS_phase_field_opt.py", line 311, in f
    self.solve_pde()
  File "AS_phase_field_opt.py", line 469, in solve_pde
    self.solver_pde.solve()
RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to solve nonlinear system with PETScSNESSolver.
*** Reason:  Solver did not converge.
*** Where:   This error was encountered inside PETScSNESSolver.cpp.
*** Process: 0
*** 
*** DOLFIN version: 2018.1.0
*** Git changeset:  948dc42cc4e06ed9227d0201ad50f94ac94cbf9f
*** -------------------------------------------------------------------------

Traceback (most recent call last):
  File "AS_phase_field_opt.py", line 806, in <module>
    main()
  File "AS_phase_field_opt.py", line 138, in main
    iter = solver_TAO_alpha.solve(problem_alpha, alpha.vector(), lb_alpha.vector(), ub_alpha.vector())
  File "AS_phase_field_opt.py", line 311, in f
    self.solve_pde()
  File "AS_phase_field_opt.py", line 469, in solve_pde
    self.solver_pde.solve()
RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to solve nonlinear system with PETScSNESSolver.
*** Reason:  Solver did not converge.
*** Where:   This error was encountered inside PETScSNESSolver.cpp.
*** Process: 6
*** 
*** DOLFIN version: 2018.1.0
*** Git changeset:  948dc42cc4e06ed9227d0201ad50f94ac94cbf9f
*** -------------------------------------------------------------------------

Traceback (most recent call last):
  File "AS_phase_field_opt.py", line 806, in <module>
    main()
  File "AS_phase_field_opt.py", line 138, in main
    iter = solver_TAO_alpha.solve(problem_alpha, alpha.vector(), lb_alpha.vector(), ub_alpha.vector())
  File "AS_phase_field_opt.py", line 311, in f
    self.solve_pde()
  File "AS_phase_field_opt.py", line 469, in solve_pde
    self.solver_pde.solve()
RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to solve nonlinear system with PETScSNESSolver.
*** Reason:  Solver did not converge.
*** Where:   This error was encountered inside PETScSNESSolver.cpp.
*** Process: 4
*** 
*** DOLFIN version: 2018.1.0
*** Git changeset:  948dc42cc4e06ed9227d0201ad50f94ac94cbf9f
*** -------------------------------------------------------------------------

Traceback (most recent call last):
  File "AS_phase_field_opt.py", line 806, in <module>
    main()
  File "AS_phase_field_opt.py", line 138, in main
    iter = solver_TAO_alpha.solve(problem_alpha, alpha.vector(), lb_alpha.vector(), ub_alpha.vector())
  File "AS_phase_field_opt.py", line 311, in f
    self.solve_pde()
  File "AS_phase_field_opt.py", line 469, in solve_pde
    self.solver_pde.solve()
RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to solve nonlinear system with PETScSNESSolver.
*** Reason:  Solver did not converge.
*** Where:   This error was encountered inside PETScSNESSolver.cpp.
*** Process: 7
*** 
*** DOLFIN version: 2018.1.0
*** Git changeset:  948dc42cc4e06ed9227d0201ad50f94ac94cbf9f
*** -------------------------------------------------------------------------

Traceback (most recent call last):
  File "AS_phase_field_opt.py", line 806, in <module>
    main()
  File "AS_phase_field_opt.py", line 138, in main
    iter = solver_TAO_alpha.solve(problem_alpha, alpha.vector(), lb_alpha.vector(), ub_alpha.vector())
  File "AS_phase_field_opt.py", line 311, in f
    self.solve_pde()
  File "AS_phase_field_opt.py", line 469, in solve_pde
    self.solver_pde.solve()
RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to solve nonlinear system with PETScSNESSolver.
*** Reason:  Solver did not converge.
*** Where:   This error was encountered inside PETScSNESSolver.cpp.
*** Process: 3
*** 
*** DOLFIN version: 2018.1.0
*** Git changeset:  948dc42cc4e06ed9227d0201ad50f94ac94cbf9f
*** -------------------------------------------------------------------------

Traceback (most recent call last):
  File "AS_phase_field_opt.py", line 806, in <module>
    main()
  File "AS_phase_field_opt.py", line 138, in main
    iter = solver_TAO_alpha.solve(problem_alpha, alpha.vector(), lb_alpha.vector(), ub_alpha.vector())
  File "AS_phase_field_opt.py", line 311, in f
    self.solve_pde()
  File "AS_phase_field_opt.py", line 469, in solve_pde
    self.solver_pde.solve()
RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to solve nonlinear system with PETScSNESSolver.
*** Reason:  Solver did not converge.
*** Where:   This error was encountered inside PETScSNESSolver.cpp.
*** Process: 1
*** 
*** DOLFIN version: 2018.1.0
*** Git changeset:  948dc42cc4e06ed9227d0201ad50f94ac94cbf9f
*** -------------------------------------------------------------------------

Traceback (most recent call last):
  File "AS_phase_field_opt.py", line 806, in <module>
    main()
  File "AS_phase_field_opt.py", line 138, in main
    iter = solver_TAO_alpha.solve(problem_alpha, alpha.vector(), lb_alpha.vector(), ub_alpha.vector())
  File "AS_phase_field_opt.py", line 311, in f
    self.solve_pde()
  File "AS_phase_field_opt.py", line 469, in solve_pde
    self.solver_pde.solve()
RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to solve nonlinear system with PETScSNESSolver.
*** Reason:  Solver did not converge.
*** Where:   This error was encountered inside PETScSNESSolver.cpp.
*** Process: 2
*** 
*** DOLFIN version: 2018.1.0
*** Git changeset:  948dc42cc4e06ed9227d0201ad50f94ac94cbf9f
*** -------------------------------------------------------------------------

Traceback (most recent call last):
  File "AS_phase_field_opt.py", line 806, in <module>
    main()
  File "AS_phase_field_opt.py", line 138, in main
    iter = solver_TAO_alpha.solve(problem_alpha, alpha.vector(), lb_alpha.vector(), ub_alpha.vector())
  File "AS_phase_field_opt.py", line 311, in f
    self.solve_pde()
  File "AS_phase_field_opt.py", line 469, in solve_pde
    self.solver_pde.solve()
RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to solve nonlinear system with PETScSNESSolver.
*** Reason:  Solver did not converge.
*** Where:   This error was encountered inside PETScSNESSolver.cpp.
*** Process: 5
*** 
*** DOLFIN version: 2018.1.0
*** Git changeset:  948dc42cc4e06ed9227d0201ad50f94ac94cbf9f
*** -------------------------------------------------------------------------

